name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for reporting an issue! Welcome to Async Selector Kit!'
        pr-message: 'Thanks for your first PR! Welcome to Async Selector Kit!'
